apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: sampleapp
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
      - name: sampleapp
        image: gcr.io/cicd-devops-248909/hello-la
        ports:
        - containerPort: 80